[2023-12-20 13:01:18,097: INFO: main:Welcome to the jungle!]
[2023-12-22 10:50:56,565: INFO: stage_01_data_ingestion:>>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-22 10:50:56,579: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-22 10:50:56,580: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-22 10:50:56,582: INFO: common:created directory at: artifacts]
[2023-12-22 10:50:56,585: INFO: common:created directory at: artifacts/data_ingestion]
[2023-12-22 10:51:04,754: INFO: data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: B6B4:309ECE:16BEAF:26D841:65851CB9
Accept-Ranges: bytes
Date: Fri, 22 Dec 2023 05:20:59 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100032-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1703222458.106404,VS0,VE1097
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 614bc284c0784f9a5afbdda5fd33adebc849c421
Expires: Fri, 22 Dec 2023 05:25:59 GMT
Source-Age: 1

]
[2023-12-22 10:51:05,492: INFO: stage_01_data_ingestion:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-22 14:29:08,295: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-22 14:29:09,327: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-22 14:29:14,583: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-22 14:29:14,597: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-22 14:29:14,606: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-22 14:29:14,617: INFO: common:created directory at: artifacts]
[2023-12-22 14:29:14,630: INFO: common:created directory at: artifacts/data_ingestion]
[2023-12-22 14:29:22,979: INFO: data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 4F70:307927:188417:29463D:65854FE4
Accept-Ranges: bytes
Date: Fri, 22 Dec 2023 08:59:17 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100030-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1703235557.842954,VS0,VE902
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 08c31d1e10860289104dadfe394a89291d97d488
Expires: Fri, 22 Dec 2023 09:04:17 GMT
Source-Age: 1

]
[2023-12-22 14:29:24,574: INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-22 14:29:24,579: INFO: main:*******************]
[2023-12-22 14:29:24,641: INFO: main:>>>>>> stage Prepare base model started <<<<<<]
[2023-12-22 14:29:24,717: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-22 14:29:24,772: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-22 14:29:24,842: INFO: common:created directory at: artifacts]
[2023-12-22 14:29:24,935: INFO: common:created directory at: artifacts/prepare_base_model]
[2023-12-22 14:29:27,280: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2023-12-22 14:29:33,234: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2023-12-22 14:29:34,050: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-22 14:29:34,748: INFO: main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-22 14:56:54,240: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-22 14:56:54,472: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-22 14:56:55,130: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-22 14:56:55,157: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-22 14:56:55,167: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-22 14:56:55,170: INFO: common:created directory at: artifacts]
[2023-12-22 14:56:55,173: INFO: common:created directory at: artifacts/data_ingestion]
[2023-12-22 14:57:03,041: INFO: data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 4F70:307927:188417:29463D:65854FE4
Accept-Ranges: bytes
Date: Fri, 22 Dec 2023 09:26:56 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100021-HYD
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1703237216.333913,VS0,VE313
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 1fe5229b80b17ce18a95aeea6d67f70a3084b2b4
Expires: Fri, 22 Dec 2023 09:31:56 GMT
Source-Age: 0

]
[2023-12-22 14:57:03,487: INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-22 14:57:03,488: INFO: main:*******************]
[2023-12-22 14:57:03,489: INFO: main:>>>>>> stage Prepare base model started <<<<<<]
[2023-12-22 14:57:03,492: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-22 14:57:03,495: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-22 14:57:03,497: INFO: common:created directory at: artifacts]
[2023-12-22 14:57:03,502: INFO: common:created directory at: artifacts/prepare_base_model]
[2023-12-22 14:57:03,695: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2023-12-22 14:57:03,789: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2023-12-22 14:57:04,334: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-22 14:57:05,036: INFO: main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-22 14:57:05,043: INFO: main:*******************]
[2023-12-22 14:57:05,058: INFO: main:>>>>>> stage Training started <<<<<<]
[2023-12-22 14:57:05,088: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-22 14:57:05,110: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-22 14:57:05,119: INFO: common:created directory at: artifacts]
[2023-12-22 14:57:05,124: ERROR: main:name 'os' is not defined]
Traceback (most recent call last):
  File "c:\Users\indtal\OneDrive - Vanderlande\Desktop\Misc\Projects - 2024\chicken-disease-classification\main.py", line 34, in <module>
    model_trainer.main()
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\pipeline\stage_03_training.py", line 17, in main
    prepare_callbacks_config = config.get_prepare_callback_config()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\config\configuration.py", line 59, in get_prepare_callback_config
    model_ckpt_dir = os.path.dirname(config.checkpoint_model_filepath)
                     ^^
NameError: name 'os' is not defined
[2023-12-22 14:58:35,543: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-22 14:58:35,862: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-22 14:58:36,627: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-22 14:58:36,630: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-22 14:58:36,632: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-22 14:58:36,633: INFO: common:created directory at: artifacts]
[2023-12-22 14:58:36,635: INFO: common:created directory at: artifacts/data_ingestion]
[2023-12-22 14:58:36,636: INFO: data_ingestion:File already exists of size: ~ 11345 KB]
[2023-12-22 14:58:37,391: ERROR: main:[Errno 13] Permission denied: 'artifacts\\data_ingestion\\Chicken-fecal-images\\Healthy\\healthy.145.jpg']
Traceback (most recent call last):
  File "c:\Users\indtal\OneDrive - Vanderlande\Desktop\Misc\Projects - 2024\chicken-disease-classification\main.py", line 10, in <module>
    obj.main()
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\components\data_ingestion.py", line 37, in extract_zip_file
    zip_ref.extractall(unzip_path)
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\zipfile.py", line 1681, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\zipfile.py", line 1735, in _extract_member
    open(targetpath, "wb") as target:
    ^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'artifacts\\data_ingestion\\Chicken-fecal-images\\Healthy\\healthy.145.jpg'
[2023-12-22 14:59:11,534: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-22 14:59:11,722: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-22 14:59:12,316: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-22 14:59:12,320: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-22 14:59:12,321: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-22 14:59:12,324: INFO: common:created directory at: artifacts]
[2023-12-22 14:59:12,326: INFO: common:created directory at: artifacts/data_ingestion]
[2023-12-22 14:59:20,221: INFO: data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 4F70:307927:188417:29463D:65854FE4
Accept-Ranges: bytes
Date: Fri, 22 Dec 2023 09:29:13 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100024-HYD
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1703237353.364499,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 444167ce773537b619407bbac2c67162538fdc30
Expires: Fri, 22 Dec 2023 09:34:13 GMT
Source-Age: 137

]
[2023-12-22 14:59:20,744: INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-22 14:59:20,745: INFO: main:*******************]
[2023-12-22 14:59:20,746: INFO: main:>>>>>> stage Prepare base model started <<<<<<]
[2023-12-22 14:59:20,754: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-22 14:59:20,756: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-22 14:59:20,767: INFO: common:created directory at: artifacts]
[2023-12-22 14:59:20,772: INFO: common:created directory at: artifacts/prepare_base_model]
[2023-12-22 14:59:21,151: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2023-12-22 14:59:21,289: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2023-12-22 14:59:21,997: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-22 14:59:22,562: INFO: main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-22 14:59:22,563: INFO: main:*******************]
[2023-12-22 14:59:22,564: INFO: main:>>>>>> stage Training started <<<<<<]
[2023-12-22 14:59:22,570: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-22 14:59:22,573: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-22 14:59:22,576: INFO: common:created directory at: artifacts]
[2023-12-22 14:59:22,582: INFO: common:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-22 14:59:22,584: INFO: common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-22 14:59:22,591: ERROR: main:'WindowsPath' object has no attribute 'endswith']
Traceback (most recent call last):
  File "c:\Users\indtal\OneDrive - Vanderlande\Desktop\Misc\Projects - 2024\chicken-disease-classification\main.py", line 34, in <module>
    model_trainer.main()
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\pipeline\stage_03_training.py", line 19, in main
    callback_list = prepare_callbacks.get_tb_ckpt_callbacks()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\components\prepare_callbacks.py", line 36, in get_tb_ckpt_callbacks
    self._create_ckpt_callbacks
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\components\prepare_callbacks.py", line 27, in _create_ckpt_callbacks
    return tf.keras.callbacks.ModelCheckpoint(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\callbacks.py", line 1369, in __init__
    if filepath and filepath.endswith(".keras") and options is not None:
                    ^^^^^^^^^^^^^^^^^
AttributeError: 'WindowsPath' object has no attribute 'endswith'
[2023-12-24 18:27:25,549: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-24 18:27:25,885: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-24 18:27:26,922: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-24 18:27:26,925: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 18:27:26,928: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 18:27:26,929: INFO: common:created directory at: artifacts]
[2023-12-24 18:27:26,930: INFO: common:created directory at: artifacts/data_ingestion]
[2023-12-24 18:27:26,931: INFO: data_ingestion:File already exists of size: ~ 11345 KB]
[2023-12-24 18:27:30,211: INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-24 18:27:30,212: INFO: main:*******************]
[2023-12-24 18:27:30,212: INFO: main:>>>>>> stage Prepare base model started <<<<<<]
[2023-12-24 18:27:30,217: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 18:27:30,220: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 18:27:30,222: INFO: common:created directory at: artifacts]
[2023-12-24 18:27:30,223: INFO: common:created directory at: artifacts/prepare_base_model]
[2023-12-24 18:27:30,523: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2023-12-24 18:27:30,743: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2023-12-24 18:27:31,410: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-24 18:27:31,891: INFO: main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-24 18:27:31,894: INFO: main:*******************]
[2023-12-24 18:27:31,895: INFO: main:>>>>>> stage Training started <<<<<<]
[2023-12-24 18:27:31,902: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 18:27:31,912: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 18:27:31,914: INFO: common:created directory at: artifacts]
[2023-12-24 18:27:31,916: INFO: common:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-24 18:27:31,918: INFO: common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-24 18:27:31,924: ERROR: main:'WindowsPath' object has no attribute 'endswith']
Traceback (most recent call last):
  File "c:\Users\indtal\OneDrive - Vanderlande\Desktop\Misc\Projects - 2024\chicken-disease-classification\main.py", line 35, in <module>
    model_trainer.main()
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\pipeline\stage_03_training.py", line 19, in main
    callback_list = prepare_callbacks.get_tb_ckpt_callbacks()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\components\prepare_callbacks.py", line 36, in get_tb_ckpt_callbacks
    self._create_ckpt_callbacks
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\components\prepare_callbacks.py", line 27, in _create_ckpt_callbacks
    return tf.keras.callbacks.ModelCheckpoint(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\callbacks.py", line 1369, in __init__
    if filepath and filepath.endswith(".keras") and options is not None:
                    ^^^^^^^^^^^^^^^^^
AttributeError: 'WindowsPath' object has no attribute 'endswith'
[2023-12-24 18:47:45,155: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-24 18:47:45,572: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-24 18:47:46,845: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-24 18:47:46,859: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 18:47:46,865: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 18:47:46,869: INFO: common:created directory at: artifacts]
[2023-12-24 18:47:46,873: INFO: common:created directory at: artifacts/data_ingestion]
[2023-12-24 18:47:46,875: INFO: data_ingestion:File already exists of size: ~ 11345 KB]
[2023-12-24 18:47:47,388: INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-24 18:47:47,389: INFO: main:*******************]
[2023-12-24 18:47:47,390: INFO: main:>>>>>> stage Prepare base model started <<<<<<]
[2023-12-24 18:47:47,401: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 18:47:47,409: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 18:47:47,411: INFO: common:created directory at: artifacts]
[2023-12-24 18:47:47,412: INFO: common:created directory at: artifacts/prepare_base_model]
[2023-12-24 18:47:47,646: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2023-12-24 18:47:47,863: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2023-12-24 18:47:48,642: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-24 18:47:49,331: INFO: main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-24 18:47:49,333: INFO: main:*******************]
[2023-12-24 18:47:49,334: INFO: main:>>>>>> stage Training started <<<<<<]
[2023-12-24 18:47:49,350: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 18:47:49,362: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 18:47:49,363: INFO: common:created directory at: artifacts]
[2023-12-24 18:48:15,860: INFO: common:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-24 18:48:15,862: INFO: common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-24 18:48:44,875: ERROR: main:'WindowsPath' object has no attribute 'endswith']
Traceback (most recent call last):
  File "C:\Users\indtal\OneDrive - Vanderlande\Desktop\Misc\Projects - 2024\chicken-disease-classification\main.py", line 35, in <module>
    model_trainer.main()
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\pipeline\stage_03_training.py", line 19, in main
    callback_list = prepare_callbacks.get_tb_ckpt_callbacks()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\components\prepare_callbacks.py", line 36, in get_tb_ckpt_callbacks
    self._create_ckpt_callbacks
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\components\prepare_callbacks.py", line 27, in _create_ckpt_callbacks
    return tf.keras.callbacks.ModelCheckpoint(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\callbacks.py", line 1369, in __init__
    if filepath and filepath.endswith(".keras") and options is not None:
                    ^^^^^^^^^^^^^^^^^
AttributeError: 'WindowsPath' object has no attribute 'endswith'
[2023-12-24 18:51:45,639: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\tensorflow_estimator\python\estimator\util.py:74: The name tf.train.SessionRunHook is deprecated. Please use tf.estimator.SessionRunHook instead.
]
[2023-12-24 19:09:19,679: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-24 19:09:19,846: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-24 19:09:20,347: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-24 19:09:20,356: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:09:20,362: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:09:20,364: INFO: common:created directory at: artifacts]
[2023-12-24 19:09:20,364: INFO: common:created directory at: artifacts/data_ingestion]
[2023-12-24 19:09:20,366: INFO: data_ingestion:File already exists of size: ~ 11345 KB]
[2023-12-24 19:09:20,797: INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-24 19:09:20,798: INFO: main:*******************]
[2023-12-24 19:09:20,799: INFO: main:>>>>>> stage Prepare base model started <<<<<<]
[2023-12-24 19:09:20,802: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:09:20,804: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:09:20,806: INFO: common:created directory at: artifacts]
[2023-12-24 19:09:20,810: INFO: common:created directory at: artifacts/prepare_base_model]
[2023-12-24 19:09:20,980: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2023-12-24 19:09:21,060: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2023-12-24 19:09:21,427: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-24 19:09:21,712: INFO: main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-24 19:09:21,716: INFO: main:*******************]
[2023-12-24 19:09:21,716: INFO: main:>>>>>> stage Training started <<<<<<]
[2023-12-24 19:09:21,726: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:09:21,730: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:09:21,734: INFO: common:created directory at: artifacts]
[2023-12-24 19:09:21,736: INFO: common:created directory at: artifacts\prepare_callbacks]
[2023-12-24 19:09:21,737: INFO: common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-24 19:09:21,740: ERROR: main:'WindowsPath' object has no attribute 'endswith']
Traceback (most recent call last):
  File "c:\Users\indtal\OneDrive - Vanderlande\Desktop\Misc\Projects - 2024\chicken-disease-classification\main.py", line 35, in <module>
    model_trainer.main()
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\pipeline\stage_03_training.py", line 19, in main
    callback_list = prepare_callbacks.get_tb_ckpt_callbacks()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\components\prepare_callbacks.py", line 36, in get_tb_ckpt_callbacks
    self._create_ckpt_callbacks
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\components\prepare_callbacks.py", line 27, in _create_ckpt_callbacks
    return tf.keras.callbacks.ModelCheckpoint(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\callbacks.py", line 1369, in __init__
    if filepath and filepath.endswith(".keras") and options is not None:
                    ^^^^^^^^^^^^^^^^^
AttributeError: 'WindowsPath' object has no attribute 'endswith'
[2023-12-24 19:10:33,006: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-24 19:10:33,282: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-24 19:10:34,079: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-24 19:10:34,097: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:10:34,106: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:10:34,108: INFO: common:created directory at: artifacts]
[2023-12-24 19:10:34,109: INFO: common:created directory at: artifacts/data_ingestion]
[2023-12-24 19:10:34,110: INFO: data_ingestion:File already exists of size: ~ 11345 KB]
[2023-12-24 19:10:34,568: INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-24 19:10:34,569: INFO: main:*******************]
[2023-12-24 19:10:34,569: INFO: main:>>>>>> stage Prepare base model started <<<<<<]
[2023-12-24 19:10:34,580: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:10:34,589: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:10:34,590: INFO: common:created directory at: artifacts]
[2023-12-24 19:10:34,591: INFO: common:created directory at: artifacts/prepare_base_model]
[2023-12-24 19:10:34,986: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2023-12-24 19:10:35,367: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2023-12-24 19:10:35,996: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-24 19:10:36,452: INFO: main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-24 19:10:36,454: INFO: main:*******************]
[2023-12-24 19:10:36,454: INFO: main:>>>>>> stage Training started <<<<<<]
[2023-12-24 19:10:36,470: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:10:36,477: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:10:36,478: INFO: common:created directory at: artifacts]
[2023-12-24 19:10:42,213: INFO: common:created directory at: artifacts\prepare_callbacks]
[2023-12-24 19:10:42,214: INFO: common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-24 19:10:48,612: ERROR: main:'WindowsPath' object has no attribute 'endswith']
Traceback (most recent call last):
  File "C:\Users\indtal\OneDrive - Vanderlande\Desktop\Misc\Projects - 2024\chicken-disease-classification\main.py", line 35, in <module>
    model_trainer.main()
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\pipeline\stage_03_training.py", line 19, in main
    callback_list = prepare_callbacks.get_tb_ckpt_callbacks()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\components\prepare_callbacks.py", line 36, in get_tb_ckpt_callbacks
    self._create_ckpt_callbacks
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\components\prepare_callbacks.py", line 27, in _create_ckpt_callbacks
    return tf.keras.callbacks.ModelCheckpoint(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\callbacks.py", line 1369, in __init__
    if filepath and filepath.endswith(".keras") and options is not None:
                    ^^^^^^^^^^^^^^^^^
AttributeError: 'WindowsPath' object has no attribute 'endswith'
[2023-12-24 19:13:08,644: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-24 19:13:08,937: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-24 19:13:09,739: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-24 19:13:09,752: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:13:09,760: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:13:09,761: INFO: common:created directory at: artifacts]
[2023-12-24 19:13:09,762: INFO: common:created directory at: artifacts/data_ingestion]
[2023-12-24 19:13:09,763: INFO: data_ingestion:File already exists of size: ~ 11345 KB]
[2023-12-24 19:13:10,215: INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-24 19:13:10,216: INFO: main:*******************]
[2023-12-24 19:13:10,217: INFO: main:>>>>>> stage Prepare base model started <<<<<<]
[2023-12-24 19:13:10,231: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:13:10,255: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:13:10,259: INFO: common:created directory at: artifacts]
[2023-12-24 19:13:10,263: INFO: common:created directory at: artifacts/prepare_base_model]
[2023-12-24 19:13:10,535: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2023-12-24 19:13:10,670: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2023-12-24 19:13:11,449: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-24 19:13:11,995: INFO: main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-24 19:13:11,997: INFO: main:*******************]
[2023-12-24 19:13:11,998: INFO: main:>>>>>> stage Training started <<<<<<]
[2023-12-24 19:13:12,030: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:13:12,045: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:13:12,048: INFO: common:created directory at: artifacts]
[2023-12-24 19:13:16,258: INFO: common:created directory at: artifacts\prepare_callbacks]
[2023-12-24 19:13:16,259: INFO: common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-24 19:13:17,399: ERROR: main:'WindowsPath' object has no attribute 'endswith']
Traceback (most recent call last):
  File "C:\Users\indtal\OneDrive - Vanderlande\Desktop\Misc\Projects - 2024\chicken-disease-classification\main.py", line 35, in <module>
    model_trainer.main()
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\pipeline\stage_03_training.py", line 19, in main
    callback_list = prepare_callbacks.get_tb_ckpt_callbacks()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\components\prepare_callbacks.py", line 37, in get_tb_ckpt_callbacks
    self._create_ckpt_callbacks
  File "c:\users\indtal\onedrive - vanderlande\desktop\misc\projects - 2024\chicken-disease-classification\src\cnnClassifier\components\prepare_callbacks.py", line 28, in _create_ckpt_callbacks
    return tf.keras.callbacks.ModelCheckpoint(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\callbacks.py", line 1369, in __init__
    if filepath and filepath.endswith(".keras") and options is not None:
                    ^^^^^^^^^^^^^^^^^
AttributeError: 'WindowsPath' object has no attribute 'endswith'
[2023-12-24 19:31:38,901: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-24 19:31:39,108: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-24 19:31:39,729: INFO: main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-24 19:31:39,743: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:31:39,748: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:31:39,748: INFO: common:created directory at: artifacts]
[2023-12-24 19:31:39,749: INFO: common:created directory at: artifacts/data_ingestion]
[2023-12-24 19:31:39,750: INFO: data_ingestion:File already exists of size: ~ 11345 KB]
[2023-12-24 19:31:41,547: INFO: main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-24 19:31:41,549: INFO: main:*******************]
[2023-12-24 19:31:41,555: INFO: main:>>>>>> stage Prepare base model started <<<<<<]
[2023-12-24 19:31:41,577: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:31:41,581: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:31:41,584: INFO: common:created directory at: artifacts]
[2023-12-24 19:31:41,589: INFO: common:created directory at: artifacts/prepare_base_model]
[2023-12-24 19:31:41,846: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2023-12-24 19:31:41,975: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2023-12-24 19:31:42,685: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-24 19:31:43,086: INFO: main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-12-24 19:31:43,088: INFO: main:*******************]
[2023-12-24 19:31:43,088: INFO: main:>>>>>> stage Training started <<<<<<]
[2023-12-24 19:31:43,090: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:31:43,092: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:31:43,093: INFO: common:created directory at: artifacts]
[2023-12-24 19:31:43,094: INFO: common:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-24 19:31:43,096: INFO: common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-24 19:31:43,104: INFO: common:created directory at: artifacts\training]
[2023-12-24 19:31:44,403: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.
]
[2023-12-24 19:32:28,597: INFO: main:>>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-24 19:32:28,599: INFO: main:*******************]
[2023-12-24 19:32:28,602: INFO: main:>>>>>> stage Evaluation stage started <<<<<<]
[2023-12-24 19:32:28,607: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:32:28,612: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:32:28,614: INFO: common:created directory at: artifacts]
[2023-12-24 19:32:43,322: INFO: common:json file saved at: scores.json]
[2023-12-24 19:32:43,323: INFO: main:>>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-24 19:54:35,967: INFO: stage_01_data_ingestion:>>>>>> stage Data Ingestion stage started <<<<<<]
[2023-12-24 19:54:35,972: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:54:35,975: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:54:35,976: INFO: common:created directory at: artifacts]
[2023-12-24 19:54:35,978: INFO: common:created directory at: artifacts/data_ingestion]
[2023-12-24 19:54:43,510: INFO: data_ingestion:artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 98C6:30CBFA:227ECD:3CEF5F:65883F25
Accept-Ranges: bytes
Date: Sun, 24 Dec 2023 14:24:38 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100021-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1703427878.599507,VS0,VE884
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 131d81a67bb9c01739176a5809b4cc164f30d67f
Expires: Sun, 24 Dec 2023 14:29:38 GMT
Source-Age: 1

]
[2023-12-24 19:54:44,191: INFO: stage_01_data_ingestion:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-12-24 19:55:07,174: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-24 19:55:07,549: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-24 19:55:08,694: INFO: stage_02_prepare_base_model:*******************]
[2023-12-24 19:55:08,695: INFO: stage_02_prepare_base_model:>>>>>> stage Prepare base model stage started <<<<<<]
[2023-12-24 19:55:08,700: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:55:08,704: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:55:08,705: INFO: common:created directory at: artifacts]
[2023-12-24 19:55:08,713: INFO: common:created directory at: artifacts/prepare_base_model]
[2023-12-24 19:55:08,979: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2023-12-24 19:55:09,172: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2023-12-24 19:55:09,748: WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-12-24 19:55:10,088: INFO: stage_02_prepare_base_model:>>>>>> stage Prepare base model stage completed <<<<<<

x==========x]
[2023-12-24 19:55:18,444: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-24 19:55:18,653: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-24 19:55:19,259: INFO: stage_03_training:*******************]
[2023-12-24 19:55:19,260: INFO: stage_03_training:>>>>>> stage Training started <<<<<<]
[2023-12-24 19:55:19,263: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:55:19,266: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:55:19,267: INFO: common:created directory at: artifacts]
[2023-12-24 19:55:19,273: INFO: common:created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-12-24 19:55:19,275: INFO: common:created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-12-24 19:55:19,283: INFO: common:created directory at: artifacts\training]
[2023-12-24 19:55:19,542: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2023-12-24 19:55:19,568: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2023-12-24 19:55:21,164: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.
]
[2023-12-24 19:56:20,809: INFO: stage_03_training:>>>>>> stage Training completed <<<<<<

x==========x]
[2023-12-24 19:56:35,798: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-24 19:56:36,084: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-24 19:56:36,907: INFO: stage_04_evaluation:*******************]
[2023-12-24 19:56:36,908: INFO: stage_04_evaluation:>>>>>> stage Evaluation stage started <<<<<<]
[2023-12-24 19:56:36,913: INFO: common:yaml file: config\config.yaml loaded successfully]
[2023-12-24 19:56:36,916: INFO: common:yaml file: params.yaml loaded successfully]
[2023-12-24 19:56:36,917: INFO: common:created directory at: artifacts]
[2023-12-24 19:56:37,218: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2023-12-24 19:56:37,246: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2023-12-24 19:56:38,371: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.
]
[2023-12-24 19:56:54,630: INFO: common:json file saved at: scores.json]
[2023-12-24 19:56:54,631: INFO: stage_04_evaluation:>>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-12-24 20:48:00,197: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-24 20:48:00,635: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-24 20:48:01,579: INFO: _internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.1.6:80]
[2023-12-24 20:48:01,579: INFO: _internal:[33mPress CTRL+C to quit[0m]
[2023-12-24 20:48:13,336: ERROR: app:Exception on / [GET]]
Traceback (most recent call last):
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\OneDrive - Vanderlande\Desktop\Misc\Projects - 2024\chicken-disease-classification\app.py", line 23, in home
    return render_template('index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[2023-12-24 20:48:13,353: INFO: _internal:127.0.0.1 - - [24/Dec/2023 20:48:13] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2023-12-24 20:48:13,758: INFO: _internal:127.0.0.1 - - [24/Dec/2023 20:48:13] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2023-12-24 20:48:47,083: ERROR: app:Exception on / [GET]]
Traceback (most recent call last):
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\OneDrive - Vanderlande\Desktop\Misc\Projects - 2024\chicken-disease-classification\app.py", line 23, in home
    return render_template('index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[2023-12-24 20:48:47,095: INFO: _internal:192.168.1.6 - - [24/Dec/2023 20:48:47] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2023-12-24 20:48:47,363: INFO: _internal:192.168.1.6 - - [24/Dec/2023 20:48:47] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2023-12-24 20:49:01,866: ERROR: app:Exception on / [GET]]
Traceback (most recent call last):
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\OneDrive - Vanderlande\Desktop\Misc\Projects - 2024\chicken-disease-classification\app.py", line 23, in home
    return render_template('index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[2023-12-24 20:49:01,872: INFO: _internal:127.0.0.1 - - [24/Dec/2023 20:49:01] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2023-12-24 20:49:58,020: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-24 20:49:58,257: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-24 20:49:58,749: INFO: _internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.1.6:80]
[2023-12-24 20:49:58,750: INFO: _internal:[33mPress CTRL+C to quit[0m]
[2023-12-24 20:50:58,060: ERROR: app:Exception on / [GET]]
Traceback (most recent call last):
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\OneDrive - Vanderlande\Desktop\Misc\Projects - 2024\chicken-disease-classification\app.py", line 23, in home
    return render_template('index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[2023-12-24 20:50:58,072: INFO: _internal:127.0.0.1 - - [24/Dec/2023 20:50:58] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2023-12-24 20:52:32,218: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-24 20:52:32,432: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-24 20:52:32,906: INFO: _internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.1.6:80]
[2023-12-24 20:52:32,907: INFO: _internal:[33mPress CTRL+C to quit[0m]
[2023-12-24 20:52:37,423: ERROR: app:Exception on / [GET]]
Traceback (most recent call last):
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "c:\Users\indtal\OneDrive - Vanderlande\Desktop\Misc\Projects - 2024\chicken-disease-classification\app.py", line 24, in home
    return render_template('index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[2023-12-24 20:52:37,434: INFO: _internal:127.0.0.1 - - [24/Dec/2023 20:52:37] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2023-12-24 20:54:46,037: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2023-12-24 20:54:46,273: INFO: utils:NumExpr defaulting to 8 threads.]
[2023-12-24 20:54:46,719: INFO: _internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.1.6:80]
[2023-12-24 20:54:46,720: INFO: _internal:[33mPress CTRL+C to quit[0m]
[2023-12-24 20:54:49,499: INFO: _internal:127.0.0.1 - - [24/Dec/2023 20:54:49] "GET / HTTP/1.1" 200 -]
[2023-12-24 20:55:43,894: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2023-12-24 20:55:43,932: WARNING: module_wrapper:From C:\Users\indtal\AppData\Local\anaconda3\envs\deepLearning\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2023-12-24 20:55:45,533: INFO: _internal:127.0.0.1 - - [24/Dec/2023 20:55:45] "POST /predict HTTP/1.1" 200 -]
